/**
 * Auth Keys.
 */
export const AUTH_KEYS = {
	IS_LOGIN_CONTEXT: 'IS_LOGIN_CONTEXT',
	IS_REGISTER_CONTEXT: 'IS_REGISTER_CONTEXT',
	RESET_PASSWORD_SESSION_KEY: 'RESET_PASSWORD_SESSION_KEY',
}

/**
 * Email Keys.
 */
export const EMAIL_KEYS = {
	HAS_SUCCESSFULLY_SEND_EMAIL: 'HAS_SUCCESSFULLY_SEND_EMAIL',
}

/**
 * Misc Keys.
 */
export const MISC_KEYS = {
	QUERY_TOKEN_PARAM: 'token',
	QUERY_TOKEN_FORGOT_PASSWORD: 'forgot-password',
}
